version: '3.8'

services:
  stweb:
    image: nginx:stable
    volumes:
      - ./templates:/etc/nginx/templates
      - ./certificat:/etc/certificat
      - ./dist/sheet-trainer:/opt/sheet-trainer
    ports:
      - "443:443"
      - "80:80"
